import {
  addComponent,
  addImports,
  addPlugin,
  addRouteMiddleware,
  addServerHandler,
  addServerImports,
  addServerPlugin,
  addTypeTemplate,
  createResolver,
  defineNuxtModule,
  resolvePath,
} from '@nuxt/kit';
import { defaultPublicConfig, type IamPublicConfig } from './runtime/config.js';

export type {
  IamPageMeta,
  IamPublicConfig,
  IamResourceRef,
  IamRouteLike,
} from './runtime/config.js';

export interface ModuleOptions {
  /**
   * The server file exporting the `betterIam()` instance as `iam` or as its default export. Resolved with Nuxt aliases;
   * default `~~/server/iam`.
   */
  instance: string;
  /** Where the IAM HTTP API is mounted; must match the instance's `basePath` (default `/api/iam`). */
  apiPath: string;
  /** Mount the IAM handler at `${apiPath}/**` (default true). Disable to mount it yourself. */
  handler: boolean;
  /** Run `iam.initialize()` (migrations, audit backfill) before the first use (default true). */
  initialize: boolean;
  /** Where signed-out visitors are sent by the route middleware (default `/login`). */
  loginPath: string;
  /** Require a session on every page unless it sets `definePageMeta({ iam: false })` (default false). */
  requireAuth: boolean;
  /** Load the session during server rendering (default true). */
  ssrSession: boolean;
  /** Query parameter carrying the original path to the login page; `''` disables it (default `next`). */
  nextParam: string;
}

const typeTemplate = (instancePath: string) => `// Generated by @better-iam/nuxt
import type * as instance from ${JSON.stringify(instancePath.replace(/\.(c|m)?(t|j)s$/, ''))};
import type { IamPageMeta } from '@better-iam/nuxt';

type ResolvedIam = typeof instance extends { iam: infer T } ? T : typeof instance extends { default: infer T } ? T : never;

declare module '@better-iam/nuxt/h3' {
  interface BetterIamRegister {
    iam: ResolvedIam;
  }
}
declare module '#app' {
  interface PageMeta {
    /** Better IAM access for this page: false (public), true (session), or { action, resource?, tenantId?, redirectTo? }. */
    iam?: IamPageMeta;
  }
}
declare module 'vue-router' {
  interface RouteMeta {
    iam?: IamPageMeta;
  }
}
export {};
`;

/**
 * Better IAM for Nuxt: mounts the IAM API in Nitro, installs the Vue bindings with server-rendered sessions and
 * hydrated advisory decisions, adds page-level access through `definePageMeta({ iam })`, and auto-imports the
 * composables, the `<IamCan>` component, and the server utilities.
 */
export default defineNuxtModule<ModuleOptions>({
  meta: {
    name: '@better-iam/nuxt',
    configKey: 'betterIam',
    compatibility: { nuxt: '>=3.14.0' },
  },
  defaults: {
    instance: '~~/server/iam',
    apiPath: defaultPublicConfig.apiPath,
    handler: true,
    initialize: true,
    loginPath: defaultPublicConfig.loginPath,
    requireAuth: defaultPublicConfig.requireAuth,
    ssrSession: defaultPublicConfig.ssrSession,
    nextParam: defaultPublicConfig.nextParam,
  },
  async setup(options, nuxt) {
    const resolver = createResolver(import.meta.url);
    const runtime = resolver.resolve('./runtime');
    const apiPath = `/${options.apiPath.replace(/^\/+|\/+$/g, '')}`;
    const instancePath = await resolvePath(options.instance, {
      alias: nuxt.options.alias,
      extensions: ['.ts', '.mts', '.js', '.mjs'],
    });

    const publicConfig: IamPublicConfig = {
      apiPath,
      loginPath: options.loginPath,
      requireAuth: options.requireAuth,
      ssrSession: options.ssrSession,
      nextParam: options.nextParam,
    };
    nuxt.options.runtimeConfig.public.betterIam = {
      ...publicConfig,
      ...(nuxt.options.runtimeConfig.public.betterIam as Partial<IamPublicConfig> | undefined),
    };
    nuxt.options.runtimeConfig.betterIam = {
      initialize: options.initialize,
      ...(nuxt.options.runtimeConfig.betterIam as Record<string, unknown> | undefined),
    };
    nuxt.options.build.transpile.push(runtime);

    // App side: the Vue plugin, the global access middleware, composables, and the component.
    addPlugin(resolver.resolve('./runtime/plugin'));
    addRouteMiddleware({
      name: 'better-iam',
      path: resolver.resolve('./runtime/middleware'),
      global: true,
    });
    const composables = resolver.resolve('./runtime/composables');
    addImports(
      ['useIamSession', 'useIamClient', 'useIamAuthorize', 'useIamCan', 'useIamAccessible'].map(
        (name) => ({ name, from: composables }),
      ),
    );
    addComponent({ name: 'IamCan', export: 'IamCan', filePath: composables });

    // Server side: the instance alias, the request binding, the API route, and the utilities.
    // Nitro's option types come from an augmentation this package does not load; only these two fields are touched.
    const nitro = (
      nuxt.options as unknown as {
        nitro: { alias?: Record<string, string>; externals?: { inline?: unknown[] } };
      }
    ).nitro;
    nitro.alias = { ...nitro.alias, '#better-iam/instance': instancePath };
    nitro.externals = {
      ...nitro.externals,
      inline: [...(nitro.externals?.inline ?? []), runtime],
    };
    addServerPlugin(resolver.resolve('./runtime/server/plugin'));
    if (options.handler)
      addServerHandler({
        route: `${apiPath}/**`,
        handler: resolver.resolve('./runtime/server/handler'),
      });
    const utils = resolver.resolve('./runtime/server/utils');
    addServerImports(
      [
        'useIam',
        'getIamSession',
        'requireIamSession',
        'requireIamAccess',
        'iamCan',
        'issueIamAssertion',
        'iamCredential',
      ].map((name) => ({ name, from: utils })),
    );

    addTypeTemplate(
      { filename: 'types/better-iam.d.ts', getContents: () => typeTemplate(instancePath) },
      { nuxt: true, nitro: true },
    );
  },
});
