'use client';
// Named, not `export *`: Next refuses `export *` in a 'use client' module imported from a server component.
export {
  Can,
  IamNextProvider,
  InvitationForm,
  InvitationFormView,
  PasswordResetForm,
  PasswordResetFormView,
  PasswordResetRequestForm,
  PasswordResetRequestFormView,
  ReauthenticateForm,
  ReauthenticateFormView,
  SignInForm,
  SignInFormView,
  SignUpForm,
  SignUpFormView,
  useAccessible,
  useAuthorize,
  useIamClient,
  useRouterSync,
  useSession,
  useSignOut,
} from '@better-iam/next/client';
export type {
  AuthAction,
  AuthFormError,
  AuthFormOptions,
  AuthFormState,
  AuthFormViewOf,
  AuthFormViewProps,
  AuthIntent,
  AuthMfaChallenge,
  AuthStep,
  InvitationFormProps,
  InvitationLabels,
  MfaLabels,
  PasswordResetFormProps,
  PasswordResetLabels,
  PasswordResetRequestFormProps,
  PasswordResetRequestLabels,
  ReauthenticateFormProps,
  ReauthenticateLabels,
  SignInFormProps,
  SignInLabels,
  SignUpFormProps,
  SignUpLabels,
} from '@better-iam/next/client';
