import { readFile } from 'node:fs/promises';
import { extname } from 'node:path';
import { pathToFileURL } from 'node:url';
import { validateTenantConfig, type TenantConfig } from '@better-iam/server';
import { CliError } from './errors.js';

/** What a tenant-configuration factory receives: the tenant being planned or applied and the environment. */
export interface TenantConfigContext {
  tenantId?: string;
  env: NodeJS.ProcessEnv;
}

const moduleExtensions = new Set(['.mjs', '.js', '.cjs', '.ts', '.mts']);

/**
 * Reads a desired tenant configuration for `config-plan` / `config-apply` / `config-validate`: a `.json` file, or a
 * JavaScript/TypeScript module whose default export is the configuration or a (possibly async) factory of it. Modules
 * let one file compute per-environment values (`env.STAGE === 'prod' ? ... : ...`) and share constants with the app.
 */
export async function loadTenantConfig(
  path: string,
  context: TenantConfigContext,
): Promise<unknown> {
  if (!moduleExtensions.has(extname(path).toLowerCase()))
    return JSON.parse(await readFile(path, 'utf8')) as unknown;
  const imported = (await import(pathToFileURL(path).href)) as { default?: unknown };
  const exported = imported.default;
  const value = typeof exported === 'function' ? await exported(context) : exported;
  if (value === undefined)
    throw new CliError(
      'INVALID_INPUT',
      `${path} has no default export`,
      'Export the configuration: export default defineTenantConfig({ version: 1, roles: [...] })',
    );
  return value;
}

export interface TenantConfigLint {
  valid: true;
  items: Record<string, number>;
  /** References to names this file does not define: they must already exist in the tenant, or planning fails. */
  warnings: string[];
}

/** Offline checks: the shape (`validateTenantConfig`) plus cross-references between the file's own items. */
export function lintTenantConfig(value: unknown): TenantConfigLint {
  const config: TenantConfig = validateTenantConfig(value);
  const names = (items: { name: string }[] | undefined) =>
    new Set((items ?? []).map((item) => item.name));
  const policies = names(config.policies);
  const roles = names(config.roles);
  const groups = names(config.groups);
  const warnings: string[] = [];
  const expect = (set: Set<string>, kind: string, name: string | undefined, where: string) => {
    if (name !== undefined && !set.has(name))
      warnings.push(`${where} names ${kind} "${name}", which this file does not define`);
  };
  for (const role of config.roles ?? []) {
    for (const policy of role.policies ?? [])
      expect(policies, 'policy', policy, `Role "${role.name}"`);
    for (const parent of role.inherits ?? []) expect(roles, 'role', parent, `Role "${role.name}"`);
  }
  for (const binding of config.bindings ?? []) {
    const where = `Binding ${binding.group} -> ${binding.role}`;
    expect(groups, 'group', binding.group, where);
    expect(roles, 'role', binding.role, where);
    expect(groups, 'group', binding.approverGroup, where);
  }
  for (const item of config.packages ?? []) {
    const where = `Package "${item.name}"`;
    for (const role of item.roles ?? []) expect(roles, 'role', role, where);
    for (const group of item.groups ?? []) expect(groups, 'group', group, where);
    expect(groups, 'group', item.approverGroup, where);
  }
  for (const invariant of config.invariants ?? [])
    if ('group' in invariant.subject)
      expect(groups, 'group', invariant.subject.group, `Invariant "${invariant.name}"`);
  const items: Record<string, number> = {};
  for (const key of [
    'resourceTypes',
    'policies',
    'roles',
    'groups',
    'bindings',
    'packages',
    'invariants',
    'agreements',
  ] as const)
    if (config[key]) items[key] = config[key]!.length;
  if (config.accessPolicy) items.accessPolicy = 1;
  return { valid: true, items, warnings };
}

/** `config-export --output tenant.config.ts|mjs`: the configuration as a typed module instead of JSON. */
export function tenantConfigModule(config: unknown, path: string): string {
  const body = JSON.stringify(config, null, 2);
  const header =
    '// Generated by better-iam config-export. Apply it with: better-iam config-apply --input';
  if (/\.m?ts$/i.test(path))
    return `${header} ${path.split(/[\\/]/).pop()}\nimport { defineTenantConfig } from 'better-iam/server';\n\nexport default defineTenantConfig(${body});\n`;
  return `${header} ${path.split(/[\\/]/).pop()}\n/** @type {import('better-iam/server').TenantConfig} */\nexport default ${body};\n`;
}
